"""Starter keyword -> category slug hints for merchants the user has never
categorized. Pure: no DB access. Slugs come from seed_categories.DEFAULT_TAXONOMY;
the categorizer maps them to the user's category ids and skips unknown slugs."""
import re

# (keyword, slug). Longest keyword wins; matching is word-bounded and case-insensitive.
HINTS = [
    # --- transfers / payments ---
    ("PAYMENT THANK YOU", "transfers.card_payment"),
    ("THANK YOU", "transfers.card_payment"),
    ("PAYMENT - THANK", "transfers.card_payment"),
    ("AUTOPAY PAYMENT", "transfers.card_payment"),
    ("AUTOMATIC PAYMENT", "transfers.card_payment"),
    ("ONLINE PAYMENT", "transfers.card_payment"),
    ("MOBILE PAYMENT", "transfers.card_payment"),
    ("CREDIT CARD PAYMENT", "transfers.card_payment"),
    ("CARD PAYMENT", "transfers.card_payment"),
    ("PAYMENT RECEIVED", "transfers.card_payment"),
    ("EPAY", "transfers.card_payment"),
    ("INTERAC E-TRANSFER", "transfers.internal"),
    ("E-TRANSFER", "transfers.internal"),
    ("ETRANSFER", "transfers.internal"),
    ("ONLINE TRANSFER", "transfers.internal"),
    ("TRANSFER TO", "transfers.internal"),
    ("TRANSFER FROM", "transfers.internal"),
    ("XFER", "transfers.internal"),
    ("ZELLE", "transfers.internal"),
    ("VENMO", "transfers.internal"),
    ("CASH APP", "transfers.internal"),
    ("WEALTHSIMPLE", "transfers.internal"),
    ("QUESTRADE", "transfers.internal"),
    ("VANGUARD", "transfers.internal"),
    ("FIDELITY", "transfers.internal"),
    ("ROBINHOOD", "transfers.internal"),
    # --- income ---
    ("PAYROLL", "income.salary"),
    ("DIRECT DEP", "income.salary"),
    ("DIRECT DEPOSIT", "income.salary"),
    ("DIR DEP", "income.salary"),
    ("SALARY", "income.salary"),
    ("PAY / PAYE", "income.salary"),
    ("ADP", "income.salary"),
    ("GUSTO", "income.salary"),
    ("PAYCHEX", "income.salary"),
    ("INTEREST PAID", "income.interest"),
    ("INTEREST EARNED", "income.interest"),
    ("INTEREST CREDIT", "income.interest"),
    ("DIVIDEND", "income.interest"),
    ("REFUND", "income.refunds"),
    ("CASHBACK BONUS", "income.refunds"),
    ("CASH BACK", "income.refunds"),
    ("REWARDS REDEMPTION", "income.refunds"),
    ("CANADA FED", "income.other"),
    ("CANADA PRO", "income.other"),
    ("GST/HST", "income.other"),
    ("CRA", "income.other"),
    ("IRS TREAS", "income.other"),
    # --- fees ---
    ("MONTHLY FEE", "fees.bank"),
    ("SERVICE CHARGE", "fees.bank"),
    ("SERVICE FEE", "fees.bank"),
    ("OVERDRAFT", "fees.bank"),
    ("NSF FEE", "fees.bank"),
    ("ANNUAL FEE", "fees.bank"),
    ("LATE FEE", "fees.bank"),
    ("FOREIGN TRANSACTION FEE", "fees.bank"),
    ("WIRE FEE", "fees.bank"),
    ("INTEREST CHARGE", "fees.interest"),
    ("PURCHASE INTEREST", "fees.interest"),
    ("CASH ADVANCE INTEREST", "fees.interest"),
    ("FINANCE CHARGE", "fees.interest"),
    # --- cash ---
    ("ATM WITHDRAWAL", "cash"),
    ("ATM W/D", "cash"),
    ("ATM", "cash"),
    ("CASH WITHDRAWAL", "cash"),
    ("CASH ADVANCE", "cash"),
    # --- coffee ---
    ("STARBUCKS", "dining.coffee"),
    ("TIM HORTONS", "dining.coffee"),
    ("TIMS", "dining.coffee"),
    ("DUNKIN", "dining.coffee"),
    ("SECOND CUP", "dining.coffee"),
    ("PEET", "dining.coffee"),
    ("BLUE BOTTLE", "dining.coffee"),
    ("CAFE", "dining.coffee"),
    ("COFFEE", "dining.coffee"),
    # --- delivery ---
    ("UBER EATS", "dining.delivery"),
    ("UBEREATS", "dining.delivery"),
    ("DOORDASH", "dining.delivery"),
    ("SKIP THE DISHES", "dining.delivery"),
    ("SKIPTHEDISHES", "dining.delivery"),
    ("GRUBHUB", "dining.delivery"),
    ("POSTMATES", "dining.delivery"),
    # --- bars ---
    ("BREWING", "dining.bars"),
    ("BREWERY", "dining.bars"),
    ("PUB", "dining.bars"),
    ("TAVERN", "dining.bars"),
    ("LCBO", "dining.bars"),
    ("SAQ", "dining.bars"),
    ("BEER STORE", "dining.bars"),
    ("LIQUOR", "dining.bars"),
    ("TOTAL WINE", "dining.bars"),
    # --- restaurants ---
    ("MCDONALD", "dining.restaurants"),
    ("BURGER KING", "dining.restaurants"),
    ("WENDY", "dining.restaurants"),
    ("CHIPOTLE", "dining.restaurants"),
    ("CHICK-FIL-A", "dining.restaurants"),
    ("TACO BELL", "dining.restaurants"),
    ("SUBWAY", "dining.restaurants"),
    ("PANERA", "dining.restaurants"),
    ("DOMINO", "dining.restaurants"),
    ("PIZZA", "dining.restaurants"),
    ("SUSHI", "dining.restaurants"),
    ("A&W", "dining.restaurants"),
    ("HARVEY", "dining.restaurants"),
    ("SWISS CHALET", "dining.restaurants"),
    ("BOSTON PIZZA", "dining.restaurants"),
    ("FIVE GUYS", "dining.restaurants"),
    ("SHAKE SHACK", "dining.restaurants"),
    ("POPEYES", "dining.restaurants"),
    ("KFC", "dining.restaurants"),
    ("RESTAURANT", "dining.restaurants"),
    ("BISTRO", "dining.restaurants"),
    ("GRILL", "dining.restaurants"),
    ("DINER", "dining.restaurants"),
    ("EATERY", "dining.restaurants"),
    ("KITCHEN", "dining.restaurants"),
    ("BAKERY", "dining.restaurants"),
    ("TST*", "dining.restaurants"),
    # --- groceries ---
    ("WHOLE FOODS", "groceries"),
    ("WHOLEFDS", "groceries"),
    ("TRADER JOE", "groceries"),
    ("KROGER", "groceries"),
    ("SAFEWAY", "groceries"),
    ("ALBERTSONS", "groceries"),
    ("PUBLIX", "groceries"),
    ("WEGMANS", "groceries"),
    ("ALDI", "groceries"),
    ("LIDL", "groceries"),
    ("H-E-B", "groceries"),
    ("HEB", "groceries"),
    ("MEIJER", "groceries"),
    ("SPROUTS", "groceries"),
    ("FOOD LION", "groceries"),
    ("GIANT", "groceries"),
    ("STOP & SHOP", "groceries"),
    ("JEWEL", "groceries"),
    ("MARIANO", "groceries"),
    ("LOBLAWS", "groceries"),
    ("LOBLAW", "groceries"),
    ("SOBEYS", "groceries"),
    ("METRO", "groceries"),
    ("NO FRILLS", "groceries"),
    ("NOFRILLS", "groceries"),
    ("FOOD BASICS", "groceries"),
    ("FRESHCO", "groceries"),
    ("SUPERSTORE", "groceries"),
    ("SAVE-ON-FOODS", "groceries"),
    ("SAVE ON FOODS", "groceries"),
    ("FARM BOY", "groceries"),
    ("LONGO", "groceries"),
    ("IGA", "groceries"),
    ("PROVIGO", "groceries"),
    ("MAXI", "groceries"),
    ("T&T SUPERMARKET", "groceries"),
    ("COSTCO", "groceries"),
    ("WALMART", "groceries"),
    ("WAL-MART", "groceries"),
    ("WM SUPERCENTER", "groceries"),
    ("TARGET", "shopping"),
    ("INSTACART", "groceries"),
    ("SUPERMARKET", "groceries"),
    ("GROCERY", "groceries"),
    ("MARKET", "groceries"),
    ("FOODS", "groceries"),
    # --- fuel ---
    ("SHELL", "transport.fuel"),
    ("CHEVRON", "transport.fuel"),
    ("EXXON", "transport.fuel"),
    ("MOBIL", "transport.fuel"),
    ("BP ", "transport.fuel"),
    ("SUNOCO", "transport.fuel"),
    ("MARATHON", "transport.fuel"),
    ("SPEEDWAY", "transport.fuel"),
    ("CIRCLE K", "transport.fuel"),
    ("7-ELEVEN", "transport.fuel"),
    ("WAWA", "transport.fuel"),
    ("PETRO-CANADA", "transport.fuel"),
    ("PETRO CANADA", "transport.fuel"),
    ("PETROCAN", "transport.fuel"),
    ("ESSO", "transport.fuel"),
    ("HUSKY", "transport.fuel"),
    ("PIONEER", "transport.fuel"),
    ("ULTRAMAR", "transport.fuel"),
    ("CANADIAN TIRE GAS", "transport.fuel"),
    ("COSTCO GAS", "transport.fuel"),
    ("GAS BAR", "transport.fuel"),
    ("FUEL", "transport.fuel"),
    # --- rideshare / transit / parking ---
    ("UBER", "transport.rideshare"),
    ("LYFT", "transport.rideshare"),
    ("TAXI", "transport.rideshare"),
    ("PRESTO", "transport.transit"),
    ("TTC", "transport.transit"),
    ("GO TRANSIT", "transport.transit"),
    ("METROLINX", "transport.transit"),
    ("TRANSLINK", "transport.transit"),
    ("COMPASS", "transport.transit"),
    ("STM", "transport.transit"),
    ("OC TRANSPO", "transport.transit"),
    ("MTA", "transport.transit"),
    ("CTA", "transport.transit"),
    ("METRA", "transport.transit"),
    ("BART", "transport.transit"),
    ("AMTRAK", "transport.transit"),
    ("VIA RAIL", "transport.transit"),
    ("TRANSIT", "transport.transit"),
    ("PARKING", "transport.parking"),
    ("PARKMOBILE", "transport.parking"),
    ("SPOTHERO", "transport.parking"),
    ("IMPARK", "transport.parking"),
    ("GREEN P", "transport.parking"),
    ("407 ETR", "transport.parking"),
    ("TOLL", "transport.parking"),
    ("E-ZPASS", "transport.parking"),
    ("EZPASS", "transport.parking"),
    ("JIFFY LUBE", "transport.maintenance"),
    ("MIDAS", "transport.maintenance"),
    ("CANADIAN TIRE", "transport.maintenance"),
    ("AUTOZONE", "transport.maintenance"),
    ("PEP BOYS", "transport.maintenance"),
    ("CAR WASH", "transport.maintenance"),
    ("AUTO", "transport.maintenance"),
    # --- housing ---
    ("RENT", "housing.rent"),
    ("MORTGAGE", "housing.rent"),
    ("MTG PMT", "housing.rent"),
    ("PROPERTY MGMT", "housing.rent"),
    ("HOME DEPOT", "housing.maintenance"),
    ("LOWES", "housing.maintenance"),
    ("LOWE'S", "housing.maintenance"),
    ("RONA", "housing.maintenance"),
    ("ACE HARDWARE", "housing.maintenance"),
    ("HARDWARE", "housing.maintenance"),
    ("IKEA", "housing.furniture"),
    ("WAYFAIR", "housing.furniture"),
    ("STRUCTUBE", "housing.furniture"),
    ("LEON'S", "housing.furniture"),
    ("THE BRICK", "housing.furniture"),
    # --- utilities ---
    ("HYDRO", "utilities.electricity"),
    ("ELECTRIC", "utilities.electricity"),
    ("POWER", "utilities.electricity"),
    ("ENERGY", "utilities.electricity"),
    ("COMED", "utilities.electricity"),
    ("PG&E", "utilities.electricity"),
    ("CON ED", "utilities.electricity"),
    ("DUKE ENERGY", "utilities.electricity"),
    ("ENBRIDGE", "utilities.gas"),
    ("NICOR", "utilities.gas"),
    ("PEOPLES GAS", "utilities.gas"),
    ("FORTISBC", "utilities.gas"),
    ("NATURAL GAS", "utilities.gas"),
    ("WATER BILL", "utilities.water"),
    ("WATER DEPT", "utilities.water"),
    ("WATERWORKS", "utilities.water"),
    ("COMCAST", "utilities.internet"),
    ("XFINITY", "utilities.internet"),
    ("SPECTRUM", "utilities.internet"),
    ("AT&T", "utilities.phone"),
    ("VERIZON", "utilities.phone"),
    ("T-MOBILE", "utilities.phone"),
    ("TMOBILE", "utilities.phone"),
    ("SPRINT", "utilities.phone"),
    ("ROGERS", "utilities.phone"),
    ("BELL CANADA", "utilities.phone"),
    ("BELL MOBILITY", "utilities.phone"),
    ("BELL", "utilities.phone"),
    ("TELUS", "utilities.phone"),
    ("FIDO", "utilities.phone"),
    ("KOODO", "utilities.phone"),
    ("FREEDOM MOBILE", "utilities.phone"),
    ("VIDEOTRON", "utilities.internet"),
    ("SHAW", "utilities.internet"),
    ("COGECO", "utilities.internet"),
    ("TEKSAVVY", "utilities.internet"),
    ("GOOGLE FI", "utilities.phone"),
    ("MINT MOBILE", "utilities.phone"),
    ("WIRELESS", "utilities.phone"),
    ("INTERNET", "utilities.internet"),
    # --- subscriptions ---
    ("NETFLIX", "subscriptions.streaming"),
    ("SPOTIFY", "subscriptions.streaming"),
    ("DISNEY PLUS", "subscriptions.streaming"),
    ("DISNEYPLUS", "subscriptions.streaming"),
    ("HULU", "subscriptions.streaming"),
    ("HBO MAX", "subscriptions.streaming"),
    ("CRAVE", "subscriptions.streaming"),
    ("APPLE TV", "subscriptions.streaming"),
    ("APPLE MUSIC", "subscriptions.streaming"),
    ("YOUTUBE PREMIUM", "subscriptions.streaming"),
    ("YOUTUBEPREMIUM", "subscriptions.streaming"),
    ("PRIME VIDEO", "subscriptions.streaming"),
    ("AMAZON PRIME", "subscriptions.memberships"),
    ("AMZN PRIME", "subscriptions.memberships"),
    ("PARAMOUNT", "subscriptions.streaming"),
    ("PEACOCK", "subscriptions.streaming"),
    ("AUDIBLE", "subscriptions.streaming"),
    ("SIRIUSXM", "subscriptions.streaming"),
    ("APPLE.COM/BILL", "subscriptions.software"),
    ("ITUNES", "subscriptions.software"),
    ("GOOGLE STORAGE", "subscriptions.software"),
    ("GOOGLE ONE", "subscriptions.software"),
    ("ICLOUD", "subscriptions.software"),
    ("DROPBOX", "subscriptions.software"),
    ("MICROSOFT", "subscriptions.software"),
    ("ADOBE", "subscriptions.software"),
    ("OPENAI", "subscriptions.software"),
    ("CHATGPT", "subscriptions.software"),
    ("ANTHROPIC", "subscriptions.software"),
    ("GITHUB", "subscriptions.software"),
    ("NOTION", "subscriptions.software"),
    ("1PASSWORD", "subscriptions.software"),
    ("NORDVPN", "subscriptions.software"),
    ("PLANET FITNESS", "health.fitness"),
    ("GOODLIFE", "health.fitness"),
    ("LA FITNESS", "health.fitness"),
    ("ANYTIME FITNESS", "health.fitness"),
    ("EQUINOX", "health.fitness"),
    ("PELOTON", "health.fitness"),
    ("YMCA", "health.fitness"),
    ("GYM", "health.fitness"),
    ("FITNESS", "health.fitness"),
    ("MEMBERSHIP", "subscriptions.memberships"),
    ("SUBSCRIPTION", "subscriptions.software"),
    # --- shopping ---
    ("AMAZON", "shopping.online"),
    ("AMZN", "shopping.online"),
    ("EBAY", "shopping.online"),
    ("ETSY", "shopping.online"),
    ("SHOPIFY", "shopping.online"),
    ("SHOP.APP", "shopping.online"),
    ("ALIEXPRESS", "shopping.online"),
    ("TEMU", "shopping.online"),
    ("WISH.COM", "shopping.online"),
    ("PAYPAL", "shopping.online"),
    ("BEST BUY", "shopping.electronics"),
    ("BESTBUY", "shopping.electronics"),
    ("APPLE STORE", "shopping.electronics"),
    ("APPLE.COM", "shopping.electronics"),
    ("MICRO CENTER", "shopping.electronics"),
    ("NEWEGG", "shopping.electronics"),
    ("STAPLES", "shopping.electronics"),
    ("THE SOURCE", "shopping.electronics"),
    ("OLD NAVY", "shopping.clothing"),
    ("GAP", "shopping.clothing"),
    ("H&M", "shopping.clothing"),
    ("ZARA", "shopping.clothing"),
    ("UNIQLO", "shopping.clothing"),
    ("NIKE", "shopping.clothing"),
    ("ADIDAS", "shopping.clothing"),
    ("LULULEMON", "shopping.clothing"),
    ("ARITZIA", "shopping.clothing"),
    ("NORDSTROM", "shopping.clothing"),
    ("MACY", "shopping.clothing"),
    ("TJ MAXX", "shopping.clothing"),
    ("TJMAXX", "shopping.clothing"),
    ("MARSHALLS", "shopping.clothing"),
    ("WINNERS", "shopping.clothing"),
    ("ROSS", "shopping.clothing"),
    ("HUDSON'S BAY", "shopping.clothing"),
    ("THE BAY", "shopping.clothing"),
    ("SIMONS", "shopping.clothing"),
    ("DOLLARAMA", "shopping"),
    ("DOLLAR TREE", "shopping"),
    ("DOLLAR GENERAL", "shopping"),
    ("HOMESENSE", "shopping"),
    ("HOMEGOODS", "shopping"),
    ("BED BATH", "shopping"),
    ("SHOPPERS DRUG MART", "health.pharmacy"),
    ("SHOPPERSDRUGMART", "health.pharmacy"),
    ("CVS", "health.pharmacy"),
    ("WALGREENS", "health.pharmacy"),
    ("RITE AID", "health.pharmacy"),
    ("REXALL", "health.pharmacy"),
    ("JEAN COUTU", "health.pharmacy"),
    ("LONDON DRUGS", "health.pharmacy"),
    ("PHARMACY", "health.pharmacy"),
    ("PHARMA", "health.pharmacy"),
    ("DRUG MART", "health.pharmacy"),
    ("DENTAL", "health.doctor"),
    ("DENTIST", "health.doctor"),
    ("CLINIC", "health.doctor"),
    ("MEDICAL", "health.doctor"),
    ("HOSPITAL", "health.doctor"),
    ("PHYSIO", "health.doctor"),
    ("OPTOMETR", "health.doctor"),
    ("CHIROPRACT", "health.doctor"),
    ("LABCORP", "health.doctor"),
    ("QUEST DIAGNOSTICS", "health.doctor"),
    # --- insurance ---
    ("INSURANCE", "insurance"),
    ("GEICO", "insurance"),
    ("PROGRESSIVE", "insurance"),
    ("STATE FARM", "insurance"),
    ("ALLSTATE", "insurance"),
    ("INTACT", "insurance"),
    ("DESJARDINS INS", "insurance"),
    ("MANULIFE", "insurance"),
    ("SUN LIFE", "insurance"),
    ("SUNLIFE", "insurance"),
    ("BLUE CROSS", "insurance"),
    ("AVIVA", "insurance"),
    ("TD INSURANCE", "insurance"),
    # --- travel ---
    ("AIR CANADA", "travel.flights"),
    ("WESTJET", "travel.flights"),
    ("PORTER", "travel.flights"),
    ("UNITED AIR", "travel.flights"),
    ("UNITED.COM", "travel.flights"),
    ("DELTA AIR", "travel.flights"),
    ("AMERICAN AIR", "travel.flights"),
    ("SOUTHWEST", "travel.flights"),
    ("JETBLUE", "travel.flights"),
    ("ALASKA AIR", "travel.flights"),
    ("SPIRIT AIR", "travel.flights"),
    ("FLAIR", "travel.flights"),
    ("AIRLINES", "travel.flights"),
    ("AIRLINE", "travel.flights"),
    ("EXPEDIA", "travel.flights"),
    ("KAYAK", "travel.flights"),
    ("AIRBNB", "travel.hotels"),
    ("VRBO", "travel.hotels"),
    ("MARRIOTT", "travel.hotels"),
    ("HILTON", "travel.hotels"),
    ("HYATT", "travel.hotels"),
    ("HOLIDAY INN", "travel.hotels"),
    ("BEST WESTERN", "travel.hotels"),
    ("BOOKING.COM", "travel.hotels"),
    ("HOTELS.COM", "travel.hotels"),
    ("HOTEL", "travel.hotels"),
    ("MOTEL", "travel.hotels"),
    ("HERTZ", "travel.car_rental"),
    ("AVIS", "travel.car_rental"),
    ("ENTERPRISE RENT", "travel.car_rental"),
    ("BUDGET RENT", "travel.car_rental"),
    ("NATIONAL CAR", "travel.car_rental"),
    ("TURO", "travel.car_rental"),
    # --- entertainment ---
    ("TICKETMASTER", "entertainment.events"),
    ("STUBHUB", "entertainment.events"),
    ("EVENTBRITE", "entertainment.events"),
    ("LIVE NATION", "entertainment.events"),
    ("CINEPLEX", "entertainment.events"),
    ("AMC", "entertainment.events"),
    ("CINEMA", "entertainment.events"),
    ("THEATRE", "entertainment.events"),
    ("THEATER", "entertainment.events"),
    ("MUSEUM", "entertainment.events"),
    ("STEAM", "entertainment.games"),
    ("STEAMGAMES", "entertainment.games"),
    ("PLAYSTATION", "entertainment.games"),
    ("NINTENDO", "entertainment.games"),
    ("XBOX", "entertainment.games"),
    ("EPIC GAMES", "entertainment.games"),
    ("BLIZZARD", "entertainment.games"),
    ("INDIGO", "entertainment.books"),
    ("CHAPTERS", "entertainment.books"),
    ("BARNES & NOBLE", "entertainment.books"),
    ("KINDLE", "entertainment.books"),
    ("BOOKS", "entertainment.books"),
    # --- education ---
    ("UNIVERSITY", "education"),
    ("COLLEGE", "education"),
    ("TUITION", "education"),
    ("UDEMY", "education"),
    ("COURSERA", "education"),
    ("SCHOOL", "education"),
    # --- personal care ---
    ("SEPHORA", "personal_care"),
    ("ULTA", "personal_care"),
    ("SALON", "personal_care"),
    ("BARBER", "personal_care"),
    ("SPA", "personal_care"),
    ("NAILS", "personal_care"),
    ("HAIR", "personal_care"),
    # --- gifts / donations ---
    ("DONATION", "gifts"),
    ("GOFUNDME", "gifts"),
    ("RED CROSS", "gifts"),
    ("UNITED WAY", "gifts"),
    ("CHARITY", "gifts"),
    ("FOUNDATION", "gifts"),
    ("CHURCH", "gifts"),
    # --- pets ---
    ("PETSMART", "pets"),
    ("PETCO", "pets"),
    ("PET VALU", "pets"),
    ("PETVALU", "pets"),
    ("CHEWY", "pets"),
    ("VETERINAR", "pets"),
    ("VET CLINIC", "pets"),
    ("ANIMAL HOSPITAL", "pets"),
    # --- taxes ---
    ("PROPERTY TAX", "taxes"),
    ("TAX PAYMENT", "taxes"),
    ("TURBOTAX", "taxes"),
    ("H&R BLOCK", "taxes"),
    ("IRS", "taxes"),
]


def _compile(keyword):
    escaped = re.escape(keyword.strip())
    # Word boundaries only where the keyword starts/ends with a word character;
    # symbols like "TST*" or "BP " keep their literal edges.
    start = r"(?<![A-Z0-9])" if keyword[0].isalnum() else ""
    end = r"(?![A-Z0-9])" if keyword.strip()[-1].isalnum() else ""
    return re.compile(start + escaped + end, re.IGNORECASE)


_COMPILED = sorted(
    ((len(keyword), _compile(keyword), slug, keyword) for keyword, slug in HINTS),
    key=lambda x: -x[0],
)


def lookup(merchant_key, description_clean="", description_raw=""):
    """Longest matching keyword wins; merchant_key is searched first, then the
    cleaned description, so a short generic word never beats a specific brand."""
    for text in ((merchant_key or ""), (description_clean or ""), (description_raw or "").upper()):
        if not text:
            continue
        for _n, regex, slug, _kw in _COMPILED:
            if regex.search(text):
                return slug
    return None


def all_slugs():
    return sorted({slug for _k, slug in HINTS})
