/* Help centre content: short answers and release notes. Trusted static markup (links and <b>
   only); every claim here is checked against the app, so update it with the feature it describes. */
const HELP_TOPICS = [
  { id: 'import', label: 'Importing statements', icon: 'upload' },
  { id: 'organize', label: 'Categories & rules', icon: 'tags' },
  { id: 'analyze', label: 'Budgets & reports', icon: 'bar-chart' },
  { id: 'billing', label: 'Billing & plan', icon: 'credit-card' },
  { id: 'privacy', label: 'Privacy & your data', icon: 'shield' },
  { id: 'app', label: 'Phone app & access', icon: 'download' },
];

const HELP_FAQ = [
  { id: 'formats', topic: 'import', q: 'Which files can I import?',
    a: 'CSV, Excel (.xlsx and .xls) and PDF statements, up to 25 MB each, several at once. Scanned PDFs are read with text recognition, which takes a little longer. Start on <a href="/import.html">Import</a>.',
    k: 'csv excel xlsx xls pdf scan scanned upload file size' },
  { id: 'banks', topic: 'import', q: 'Which banks are supported?',
    a: 'iSpend recognises statements from Chase, Amex, Capital One, Bank of America, Citi, Discover, PNC, Wells Fargo, RBC, TD, BMO and Scotiabank. Any other bank’s CSV works too: you match its columns once in the preview and iSpend remembers the layout for next time.',
    k: 'bank chase amex american express capital one bofa citi discover pnc wells fargo rbc td bmo scotiabank canada columns mapping layout' },
  { id: 'duplicates', topic: 'import', q: 'Will importing the same statement twice duplicate my transactions?',
    a: 'No. The preview flags rows that are already in iSpend and leaves them out unless you tick them. If an import went wrong, <b>Undo this import</b> on the final step, or discard it later from <a href="/statements.html">Statements</a>.',
    k: 'duplicate twice again same overlap undo discard remove import' },
  { id: 'signs', topic: 'import', q: 'My amounts have the wrong sign. What happened?',
    a: 'Banks write charges and payments differently. iSpend turns every statement into one convention: money out is negative, money in is positive. If a file comes out reversed (card exports often list purchases as positive numbers), use <b>Flip signs</b> in the preview before importing. If a recognised bank is wrong, please report it with the bank’s name.',
    k: 'negative positive sign reversed wrong amount debit credit income expense' },
  { id: 'categorize', topic: 'organize', q: 'How does iSpend pick a category?',
    a: 'In this order: your <a href="/rules.html">rules</a>, then merchants you have sorted before, then built-in hints for well-known shops. If you turned on AI assistance in <a href="/settings.html#ai">Settings</a>, it suggests categories for the rest. Suggestions wait in <a href="/review.html">Review</a> and are never applied until you confirm them.',
    k: 'category categorize automatic rules merchant memory ai suggestion review uncategorized' },
  { id: 'rules', topic: 'organize', q: 'How do I make a charge always go to the same category?',
    a: 'Sorting it once is usually enough: iSpend remembers the merchant. For anything more specific, such as text in the description or an amount range, create a rule on <a href="/rules.html">Rules</a>. Rules are checked top to bottom, and the first match wins.',
    k: 'always same category rule merchant remember automatic' },
  { id: 'transfers', topic: 'organize', q: 'Why are card payments and transfers left out of my spending?',
    a: 'Moving money between your own accounts isn’t spending. When iSpend finds both sides of a transfer, or you file a charge under a transfer category, it is excluded from spending and income totals. If one was left out by mistake, choose <b>Include in reports</b> on the transaction.',
    k: 'transfer credit card payment excluded spending double counted own accounts' },
  { id: 'splits', topic: 'organize', q: 'Can one transaction count toward several categories?',
    a: 'Yes. Choose <b>Split…</b> from a transaction’s menu and divide the amount across categories. Reports and budgets count each part separately. Tags label transactions across categories without changing them.',
    k: 'split divide several categories tag label' },
  { id: 'budgets', topic: 'analyze', q: 'How do budgets work?',
    a: 'Set a monthly limit per category, or one limit for all spending, on <a href="/budgets.html">Budgets</a>. Each shows how fast you are spending against the month. <b>Copy last month</b> carries the limits forward.',
    k: 'budget limit monthly pace copy last month overall' },
  { id: 'reports', topic: 'analyze', q: 'Where can I compare months or see income?',
    a: '<a href="/reports.html">Reports</a> shows spending by category, month over month, income, savings rate and cash flow, for any period. <a href="/insights.html">Insights</a> points out recurring charges and unusual spending.',
    k: 'report compare month income savings cash flow insights recurring subscription unusual' },
  { id: 'trial', topic: 'billing', q: 'What happens when my trial ends?',
    a: 'You can subscribe from <a href="/billing.html">Billing</a> at any time. If you don’t, nothing is deleted: after a short grace period iSpend becomes read-only, so you can still look at everything and download it. Reporting a problem always works.',
    k: 'trial end subscribe price plan read-only read only expired grace' },
  { id: 'cancel', topic: 'billing', q: 'How do I change or cancel my plan?',
    a: 'On <a href="/billing.html">Billing</a>, <b>Manage subscription</b> opens Stripe’s customer portal, where you can switch plans, update your card, download receipts or cancel. A cancelled plan runs until the end of the period you paid for.',
    k: 'cancel change plan card payment receipt invoice refund stripe portal' },
  { id: 'privacy', topic: 'privacy', q: 'Who can see my transactions?',
    a: 'Only you. Each account’s data is kept separate, and the iSpend team sees counts (how many statements, how many transactions), never the transactions themselves. The one exception is what you choose to send in a problem report.',
    k: 'privacy who see data admin team secure private' },
  { id: 'export', topic: 'privacy', q: 'How do I download everything or delete my account?',
    a: 'In <a href="/settings.html#data">Settings › Your data</a>: <b>Prepare a download</b> builds a copy of everything, including your original statement files, and <b>Delete my account</b> removes your account and everything in it for good.',
    k: 'export download copy backup delete account erase remove gdpr' },
  { id: 'install', topic: 'app', q: 'Can I use iSpend on my phone?',
    a: 'Yes. Open iSpend in your phone’s browser and sign in. To add it to your home screen, choose <b>Install app</b> from the More tab (Chrome and Edge), or in Safari tap Share, then <b>Add to Home Screen</b>.',
    k: 'phone mobile iphone android install app home screen pwa' },
  { id: 'password', topic: 'app', q: 'I forgot my password.',
    a: 'Use <b>Forgot your password?</b> on the sign-in page and we’ll email you a reset link. It works once and expires after an hour. Signed in already? Change it from your account menu.',
    k: 'forgot password reset sign in login locked email' },
];

/* Newest first. Keep each line to what a customer notices. */
const HELP_RELEASES = [
  { date: '2026-09-29', title: 'Help and problem reports', body: 'Answers to common questions and a way to report a problem, with screenshots, right inside iSpend.' },
  { date: '2026-09-27', title: 'Your data, your call', body: 'Download a full copy of your data, or delete your account, from Settings.' },
  { date: '2026-09-25', title: 'Built for phones', body: 'New phone navigation, bottom sheets, swipe actions on transactions, and Review and Import on the go.' },
  { date: '2026-09-21', title: 'Install iSpend', body: 'Add iSpend to your home screen, and have unfamiliar bank layouts remembered per account.' },
  { date: '2026-09-08', title: 'Budgets, tags and splits', body: 'Monthly limits with pace, free-form tags, and one transaction split across categories.' },
];
